name: Testing/Marking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      uses: cake-build/cake-action@v1
      with:
        target: Build
        verbosity: Normal
    - name: Test-Actions
      run: dotnet test --logger GitHubActions
        

